# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: Docker Build Push
description: Build and push Docker images with Buildx
author: docker
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  builder:
    description: "Builder instance"
    required: false
  context:
    description: "Build's context is the set of files located in the specified PATH or URL"
    required: false
    default: '.'
  file:
    description: "Path to the Dockerfile"
    required: false
    default: './Dockerfile'
  build-args:
    description: "Newline-delimited list of build-time variables"
    required: false
  labels:
    description: "Newline-delimited list of metadata for an image"
    required: false
  tags:
    description: "Newline-delimited list of tags"
    required: false
  pull:
    description: "Always attempt to pull a newer version of the image"
    required: false
    default: 'false'
  target:
    description: "Sets the target stage to build"
    required: false
  allow:
    description: "Allow extra privileged entitlement (eg. network.host,security.insecure)"
    required: false
  no-cache:
    description: "Do not use cache when building the image"
    required: false
    default: 'false'
  platforms:
    description: "Comma-delimited list of target platforms for build"
    required: false
  load:
    description: "Load is a shorthand for --output=type=docker"
    required: false
    default: 'false'
  push:
    description: "Push is a shorthand for --output=type=registry"
    required: false
    default: 'false'
  outputs:
    description: "Newline-delimited list of output destinations (format: type=local,dest=path)"
    required: false
  cache-from:
    description: "Newline-delimited list of external cache sources for buildx (eg. user/app:cache, type=local,src=path/to/dir)"
    required: false
  cache-to:
    description: "Newline-delimited list of cache export destinations for buildx (eg. user/app:cache, type=local,dest=path/to/dir)"
    required: false
  cache-github:
    description: "Export all the layers of all intermediate steps in the GitHub cache"
    required: false
    default: 'false'

outputs:
  digest:
    description: 'Image content-addressable identifier also called a digest'

runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/index.js'
