name: ci

on:
  push:
    branches:
      - master
      - v2-working-branch # remove when merged to master
  pull_request:
    branches:
      - master
      - v2-working-branch # remove when merged to master

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dockerfile:
          - multi
          - multi-golang
          - multi-sudo
    steps:
      -
        name: Run local registry
        run: |
          docker run -d -p 5000:5000 registry:2
      -
        name: Checkout
        uses: actions/checkout@v2.3.1
      -
        name: Set up QEMU
        uses: ./setup-qemu/ # change to docker/setup-qemu-action@master
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        id: buildx
        uses: ./setup-buildx/ # change to docker/setup-buildx-action@master
#        with:
#          driver-opt: network=host
      -
        name: Build and push
        uses: ./
        with:
          context: ./test
          file: ./test/Dockerfile-${{ matrix.dockerfile }}
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64,linux/386
          #allow: network.host,security.insecure
          #push: true
          tags: |
            localhost:5000/name/app:latest
            localhost:5000/name/app:1.0.0
      -
        name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
