name: setup-qemu-ci

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/setup-qemu-ci.yml
      - setup-qemu/**
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/setup-qemu-ci.yml
      - setup-qemu/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - tonistiigi/binfmt:latest
          - tonistiigi/binfmt:master
        platforms:
          - all
          - arm64,riscv64,arm
    steps:
      -
        name: Runner info
        run: |
          sudo apt-get install -y hwinfo
          sudo hwinfo --short
          sudo mount
      -
        name: Checkout
        uses: actions/checkout@v2.3.1
      -
        name: Set up QEMU
        id: qemu
        uses: ./setup-qemu/
        with:
          image: ${{ matrix.image }}
          platforms: ${{ matrix.platforms }}
      -
        name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}
